AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for S3 bucket resources needed for HUJI final project.

Parameters:
  PairName:
    Description: The name of the pair working on the exercise.
    Type: String
  CodePackageDate:
    Description: The date of the code package in ms.
    Type: String

Resources:
  FinalProjectCodeBaseS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub huji-lightricks-final-project-code-${PairName}-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  FinalProjectCodeBaseS3BucketName:
    Description: Name of code base bucket
    Value: !Ref FinalProjectCodeBaseS3Bucket
    Export:
      Name: !Sub huji-lightricks-final-project-code-${PairName}-bucket-name

  FinalProjectCodeBaseS3BucketArn:
    Description: ARN of code base bucket
    Value: !GetAtt FinalProjectCodeBaseS3Bucket.Arn
    Export:
      Name: !Sub huji-lightricks-final-project-code-${PairName}-bucket-arn
